#!/bin/bash
set -xeuo pipefail

ecr_url=304160530156.dkr.ecr.us-east-1.amazonaws.com

build() {
    hash=$(git ls-tree HEAD | git hash-object --stdin | cut -c 1-7)
    hash_tagged_image=$ecr_url/pypicloud:$hash
    latest_tagged_image=$ecr_url/pypicloud:latest

    docker build -t $hash_tagged_image .
    docker push $hash_tagged_image
    docker tag $hash_tagged_image $latest_tagged_image
    docker push $latest_tagged_image

    timestamp=$(date +%s)
    chart_version=0.1.$timestamp

    helm package charts/pypicloud --version $chart_version --app-version $hash --dependency-update
    chart_file=$(ls *.tgz)
    HELM_S3_MODE=3 helm s3 push $chart_file newscred-stable --ignore-if-exists
}

case "$1" in
    build)
        $*
        ;;
    *)
        echo "Usage: $0 build"
        exit 1
        ;;
esac
